=== profesorderedes/LenguajesDeMarcas/tema3/ejemplo01/receta.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="receta">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="medicamento" type="xs:string" minOccurs="0" maxOccurs="10" />
                
                <xs:element name="farmacia" type="xs:string" default="Farmacia Juaneda" />
                
                <xs:element name="edad">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="0" />
                            <xs:maxInclusive value="120" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                
                <xs:element name="nombre">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="3"/>
                            <xs:maxLength value="20"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="pago">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Gratuito"/>
                            <xs:enumeration value="Copago"/>
                            <xs:enumeration value="Íntegro"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="precio">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:fractionDigits value="2"/>
                            <xs:totalDigits value="6"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== profesorderedes/LenguajesDeMarcas/tema3/ejemplo01/receta.xml
<?xml version="1.0" encoding="UTF-8"?>

<receta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="receta.xsd">

    <medicamento>Omeprazol</medicamento>
    <medicamento>Paracetamol</medicamento>

    <farmacia>Farmacia Juaneda</farmacia>

    <edad>70</edad>

    <nombre>Francisco Santos</nombre>

    <pago>Gratuito</pago>

    <precio>2.89</precio>
    
</receta>
