=== profesorderedes/LenguajesDeMarcas/Tema3/ejemplos/actividad_final.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="classe">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="curs" />
                <xs:element ref="professor" />
                <xs:element ref="alumnes" />
            </xs:sequence>
            <xs:attribute ref="modul" use="required" />
            <xs:attribute ref="nommodul" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:attribute name="modul" type="xs:positiveInteger" />

    <xs:attribute name="nommodul" type="xs:string" />

    <xs:element name="curs">
        <xs:complexType>
            <xs:attribute ref="especialitat" use="required" />
            <xs:attribute ref="numero" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:attribute name="especialitat">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="DAW" />
                <xs:enumeration value="ASIX" />
                <xs:enumeration value="DAM" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="numero" type="xs:positiveInteger" />

    <xs:element name="professor">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nom" />
                <xs:element ref="cognom" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="nom" type="xs:string" />

    <xs:element name="cognom" type="xs:string" />

    <xs:element name="alumnes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="alumne" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="alumne">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nom" />
                <xs:element ref="cognom" />
                <xs:element ref="nota" />
            </xs:sequence>
            <xs:attribute ref="delegat" />
        </xs:complexType>
    </xs:element>

    <xs:element name="nota">
        <xs:simpleType>
            <xs:restriction base="xs:nonNegativeInteger">
                <xs:maxInclusive value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:attribute name="delegat" fixed="sí" />

</xs:schema>

=== profesorderedes/LenguajesDeMarcas/Tema3/ejemplos/actividad_final.xml
<?xml version="1.0" encoding="UTF-8"?>

<classe modul="3" nommodul="Programació bàsica"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="actividad_final.xsd">

    <curs especialitat="ASIX" numero="1" />
    <professor>
        <nom>Marcel</nom>
        <cognom>Puig</cognom>
    </professor>
    <alumnes>
        <alumne>
            <nom>Filomeno</nom>
            <cognom>Garcia</cognom>
            <nota>5</nota>
        </alumne>
        <alumne delegat="sí">
            <nom>Frederic</nom>
            <cognom>Pi</cognom>
            <nota>3</nota>
        </alumne>
        <alumne>
            <nom>Manel</nom>
            <cognom>Puigdevall</cognom>
            <nota>8</nota>
        </alumne>
    </alumnes>
</classe>
