=== profesorderedes/LenguajesDeMarcas/tema3/practica1PrimeraEval/guia.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="guia">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="cadena" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="cadena">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="programa" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="nombre" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="nombre"  type="xs:string"/>

    <xs:element name="programa">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre"/>
                <xs:element ref="descripcion"/>
                <xs:element ref="inicio"/>
                <xs:element ref="fin"/>
                <xs:element ref="links" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute ref="tipo" use="required"/>
            <xs:attribute ref="calificacion" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <xs:attribute name="tipo">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="INFORMATIVO"/>
                <xs:enumeration value="SERIE"/>
                <xs:enumeration value="PELÍCULA"/>
                <xs:enumeration value="DOCUMENTAL"/>
                <xs:enumeration value="OTROS"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="calificacion">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="\d?\d[+]"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="nombre" type="xs:string"/>

    <xs:element name="descripcion">
        <xs:complexType mixed="true">
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="b" />
            </xs:choice> 
        </xs:complexType>
    </xs:element>

    <xs:element name="b" type="xs:string"/>

    <xs:element name="inicio" type="TipoTiempo"/>

    <xs:attribute name="fecha" type="xs:date"/>

    <xs:attribute name="hora" type="xs:time"/>

    <xs:element name="fin" type="TipoTiempo"/>

    <xs:element name="links">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="link" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="link">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="nombre" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    
    <!-- Nuestros Tipos-->

    <xs:complexType name="TipoTiempo">
        <xs:attribute ref="fecha" use="required"/>
        <xs:attribute ref="hora" use="required"/>
    </xs:complexType>

</xs:schema>

=== profesorderedes/LenguajesDeMarcas/tema3/practica1PrimeraEval/guia.xml
<?xml version="1.0" encoding="UTF-8"?>

<guia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="guia.xsd">

    <cadena nombre="TVE1">
        <programa tipo="INFORMATIVO" calificacion="0+">
            <nombre>Telediario 1</nombre>
            <descripcion>Informativo, Noticias</descripcion>
            <inicio fecha="2024-11-22" hora="15:00:00" />
            <fin fecha="2024-11-22" hora="15:50:00" />
        </programa>
        <programa tipo="INFORMATIVO" calificacion="0+">
            <nombre>Informativo territorial</nombre>
            <descripcion>Informativo, Noticias. Espacio dedicado a la
                información autonómica.</descripcion>
            <inicio fecha="2024-11-22" hora="15:50:00" />
            <fin fecha="2024-11-22" hora="16:15:00" />
        </programa>
        <programa tipo="INFORMATIVO" calificacion="0+">
            <nombre>El tiempo</nombre>
            <descripcion>Información meteorológica de los próximos días a nivel
                estatal. Este espacio está avalado por el Instituto Nacional de
                Meteorología.</descripcion>
            <inicio fecha="2024-11-22" hora="16:15:00" />
            <fin fecha="2024-11-22" hora="16:30:00" />
        </programa>
        <programa tipo="SERIE" calificacion="12+">
            <nombre>Salón de té La Moderna</nombre>
            <descripcion>
                <b>Capítulo: 44, Temporada: 3 Serie</b>. Telenovela (+12). Pepita sigue fría con
                Emiliano tras la encerrona que le hizo para manipular a su esposa, y Paula se siente
                frustrada por la información que Iván le dio sobre su negocio, generando
                preocupación en sus padres. Paralelamente, Iván le admite a Mercedes que ha
                manipulado a su hermana, provocando su enfado.</descripcion>
            <inicio fecha="2024-11-22" hora="16:30:00" />
            <fin fecha="2024-11-22" hora="17:30:00" />
        </programa>
        <programa tipo="SERIE" calificacion="12+">
            <nombre>La promesa</nombre>
            <descripcion><b>Capítulo: 348, Temporada: 2</b>. Jana se disculpa con Manuel por haber
                abandonado la cena y acuerdan que Jana no va a volver a cenar con el resto de la
                familia hasta que se sienta preparada. Alonso, por su parte, accede a acompañar a su
                mujer a la fiesta de los condes de Urbizu, siempre y cuando ella abandone la guerra
                contra los duques de los Infantes.</descripcion>
            <inicio fecha="2024-11-22" hora="17:30:00" />
            <fin fecha="2024-11-22" hora="18:30:00" />
        </programa>
        <programa tipo="PELÍCULA" calificacion="16+">
            <nombre>Arma letal</nombre>
            <descripcion> Martin y Roger son dos veteranos de Vietnam que hacen de policías en Los
                Ángeles. Aunque son compañeros, son muy diferentes. Martin tiene fama de ser una
                máquina de matar y sus actuaciones no siempre se ajustan a la ley. En cambio, Roger
                es un profesional con una sólida reputación y un entorno familiar estable. <b>
                Director</b>: Richard Donner, <b>Interpretes</b>: Mel Gibson, Danny Glover, Darlene
                Love, Gary Busey, Mitch Ryan, Tom Atkins </descripcion>
            <inicio fecha="2024-11-21" hora="22:01:00" />
            <fin fecha="2024-11-21" hora="23:51:00" />
            <links>
                <link
                    nombre="FilmAffinity">https://www.filmaffinity.com/es/film453
                    476.html</link>
                <link
                    nombre="IMDB">https://www.imdb.com/title/tt0093409/</link>
            </links>
        </programa>
    </cadena>
    <cadena nombre="Paramount">
        <programa tipo="SERIE" calificacion="13+">
            <nombre>Agatha Christie: Poirot</nombre>
            <descripcion><b>Capítulo: 1, Temporada: 2</b>. Episodio: Peligro en la casa de la punta
                (I) Poirot se encuentra en un complejo hotelero lujoso y exclusivo. Allí conoce a
                una hermosa heredera cuya vida corre peligro.</descripcion>
            <inicio fecha="2024-11-22" hora="15:05:00" />
            <fin fecha="2024-11-22" hora="16:10:00" />
            <links>
                <link
                    nombre="IMDB">https://www.imdb.com/title/tt0094525/</link>
            </links>
        </programa>
        <programa tipo="SERIE" calificacion="7+">
            <nombre>Los misterios de Murdoch</nombre>
            <descripcion>
                <b>Capítulo: 2, Temporada: 9</b>, Episodio: Mark Twain. El famoso escritor Mark
                Twain sufre un atentado, debido a sus opiniones políticas, y Murdoch investiga lo
                sucedido. Sin embargo, el inspector enfrenta una disyuntiva: cumplir con su deber
                profesional o mantener el respeto de sus compatriotas.</descripcion>
            <inicio fecha="2024-11-22" hora="16:10:00" />
            <fin fecha="2024-11-22" hora="17:10:00" />
            <links>
                <link
                    nombre="FilmAffinity">https://www.filmaffinity.com/es/film166
                    375.html</link>
                <link
                    nombre="IMDB">https://www.imdb.com/title/tt1091909/</link>
            </links>
        </programa>
    </cadena>
</guia>
