<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE listado [
	<!ELEMENT listado ANY>
	<!ELEMENT participante ANY>
	<!ELEMENT nombre ANY>
	<!ELEMENT apellidos ANY>
]>

<listado>
	<participante>
		<nombre>Ana María</nombre>
		<apellidos>Pérez Casado</apellidos>
	</participante>
	<participante>
		<apellidos>López Rico</apellidos>
		<nombre>Nuria</nombre>
	</participante>
</listado>