=== profesorderedes/LenguajesDeMarcas/Tema3/ejemplo1/receta.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="receta">
		<xs:complexType>
			<xs:sequence>

				<xs:element name="medicamento" type="xs:string"
					maxOccurs="unbounded" />

				<xs:element name="farmacia" type="xs:string"
					default="Farmacia Juaneda" />

				<xs:element name="edad">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="0" />
							<xs:maxInclusive value="150" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>

				<xs:element name="nombre">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="50" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>

				<xs:element name="pago">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Íntegro" />
							<xs:enumeration value="Copago" />
							<xs:enumeration value="Gratuito" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>

				<xs:element name="dni">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="\d{8}[A-Z]" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>

				<xs:element name="medico">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="numColegiado" type="xs:integer" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>

				<xs:element name="posologia" type="TipoPosologia" />

				<xs:element name="alergias">
					<xs:complexType />
				</xs:element>

				<xs:element name="grupo_sanguineo">
					<xs:complexType>
						<xs:attribute name="tipo" type="xs:string" />
					</xs:complexType>
				</xs:element>

				<xs:element name="instrucciones">
					<xs:complexType mixed="true">
						<xs:sequence>
							<xs:element name="b" type="xs:string"
								maxOccurs="unbounded" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>

			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="TipoPosologia">
		<xs:sequence>
			<xs:element name="tomas" type="xs:positiveInteger" />
			<xs:element name="horario" type="xs:string" />
		</xs:sequence>
	</xs:complexType>



</xs:schema>

=== profesorderedes/LenguajesDeMarcas/Tema3/ejemplo1/receta.xml
<?xml version="1.0" encoding="UTF-8" ?>

<receta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="receta.xsd">

	<medicamento>Paracetamol</medicamento>
	<medicamento>Ibuprofeno</medicamento>

	<!-- El contenido de farmacia, si no se especifica, será "Farmacia Juaneda" -->
	<farmacia>Farmacia IES Son Ferrer</farmacia>

	<!-- La edad de un paciente puede ser mayor o igual a 0, y menor o igual 
		a 150 -->
	<edad>70</edad>

	<!-- El nombre del paciente no deberá exceder de 50 caracteres -->
	<nombre>Francisco Santos</nombre>

	<!-- El elemento pago puede ser: Gratuito, Copago o Íntegro -->
	<pago>Gratuito</pago>

	<!-- El elemento dni debe ser 8 cifras seguidas de una letra mayúscula -->
	<dni>19102001H</dni>

	<!-- El elemento numColegiado tiene un atributo de tipo integer -->
	<medico numColegiado="287368">Juan Luque</medico>

	<!-- El elemento posologia contiene dos elementos hijos, tomas y horario -->
	<posologia>
		<tomas>3</tomas>
		<horario>Tomar en el desayuno, comida y cena.</horario>
	</posologia>

	<!-- El elemento alergias siempre estará vacío -->
	<alergias />

	<!-- El elemento grupo_sanguineo estará vacío -->
	<grupo_sanguineo tipo="A+" />

	<!-- El elemento instrucciones tiene contenido mixto (texto mezclado con
		otros elementos) -->
	<instrucciones>
		Debe tomar la medicación <b>antes</b> de la comida, no después.
		Es <b>importante</b> no tomar más de tres dosis al día.
	</instrucciones>

</receta>

=== profesorderedes/LenguajesDeMarcas/tema3/ejemplo04/receta.xml
<?xml version="1.0" encoding="UTF-8"?>

<receta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="receta.xsd">

    <medicamento>Omeprazol</medicamento>
    <medicamento>Paracetamol</medicamento>

    <farmacia>Farmacia Juaneda</farmacia>

    <edad>70</edad>

    <nombre>Francisco Santos</nombre>

    <pago>Copago</pago>

    <precio>2.89</precio>

    <medico numColegiado="17161213">Juan Ríos</medico>

    <!-- Tipo de paciente: habitual o de urgencias -->
    <tipo_paciente>
        <paciente_urgencias/>
    </tipo_paciente>

    <posologia duracion="Cinco días">
        <tomas>3</tomas>
        <horario>Mañana, tarde y noche</horario>
    </posologia>

    <!-- Etiqueta vacía -->
    <alergias />

    <grupo_sanguineo tipo="AB+" />

    <instrucciones> Esta medicación debe tomarse en <b>ayunas</b>. No deben superarse los <b>cuatro</b>
        comprimidos al día. 
    </instrucciones>

</receta>

=== profesorderedes/LenguajesDeMarcas/Tema3/receta.xml
<?xml version="1.0" encoding="UTF-8"?>

<receta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="receta.xsd">

    <medicamento>Paracetamol</medicamento>
    <medicamento>Omeprazol</medicamento>

    <farmacia>Farmacia Juaneda</farmacia>

    <edad>70</edad>

    <nombre>Francisco Santos</nombre>

    <pago>Gratuito</pago>

    <dni>22119029H</dni>

    <medico numColegiado="171612713">Juan Ríos</medico>

    <posologia>
        <tomas>3</tomas>
        <horario>Mañana, tarde y noche</horario>
    </posologia>

</receta>
