=== profesorderedes/LenguajesDeMarcas/Tema3/masEjerciciosXSD/empleados.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="empleados">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="empleado" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="empleado">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="inicioContrato" />
				<xs:element ref="ocupaciónActual" />
				<xs:element ref="ocupacionesAnteriores" />
				<xs:element ref="jefe" minOccurs="0" />
				<xs:element ref="sueldo" />
				<xs:element ref="titulaciones" />
				<xs:element ref="sede" />
				<xs:element ref="observaciones" />
			</xs:sequence>
			<xs:attribute ref="id" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:attribute name="id" type="xs:ID" />

	<xs:element name="nombre" type="xs:string" />

	<xs:element name="inicioContrato" type="xs:date" />

	<xs:element name="ocupaciónActual" type="xs:string" />

	<xs:element name="ocupacionesAnteriores" type="xs:string" />

	<xs:element name="jefe" type="xs:IDREF" />

	<xs:element name="sueldo" type="xs:string" />

	<xs:element name="titulaciones" type="xs:string" />

	<xs:element name="sede">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Madrid" />
				<xs:enumeration value="Barcelona" />
				<xs:enumeration value="Valencia" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="observaciones">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element name="meritos" type="xs:string" minOccurs="0" />
				<xs:element name="demeritos" type="xs:string"
					minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== profesorderedes/LenguajesDeMarcas/Tema3/masEjerciciosXSD/empleados.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!-- Una empresa pretén guardar la informació dels seus empleats en xml. 
	Fes un esquema per poder modelar-ho creant nou tipus de dades. S'ha de guardar 
	el nom de l'empleat i un identificador únic com atribut, la data d'inici 
	del contracte, el lloc que ocupa i els llocs que ha ocupat, el seu cap directe 
	com una relació amb l'ID, el que cobra, tots els seus títol acadèmics, la 
	seu en que treballa d'entre les tres possibles: Madrid, Barcelona, València; 
	finalment s'ha de guardar un camp que siguin observacions on també hi pot 
	haver altres etiquetes com merits, demerits. Fes també un document que s'hi 
	ajusti, amb al menys 5 empleats. -->

<empleados
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="empleados.xsd">

	<empleado id="A1">

		<nombre>Juan</nombre>
		<inicioContrato>2000/01/25</inicioContrato>
		<ocupaciónActual>Oficial 1º</ocupaciónActual>
		<ocupacionesAnteriores>Oficial2º, Oficial3º</ocupacionesAnteriores>
		<jefe>A2</jefe>
		<sueldo>2.000</sueldo>
		<titulaciones>Técnico especialista</titulaciones>
		<sede> Barcelona</sede>
		<observaciones>
			El rendimiento de Juan es correcto.
			<meritos>Comportamiento</meritos>
			<demeritos>Falta de puntualidad ocasional</demeritos>
		</observaciones>

	</empleado>

	<empleado id="A2">

		<nombre>María</nombre>
		<inicioContrato>1995/09/07</inicioContrato>
		<ocupaciónActual>Jefa</ocupaciónActual>
		<ocupacionesAnteriores>Administración, Jefa Administración
		</ocupacionesAnteriores>
		<jefe></jefe>
		<sueldo>2.800</sueldo>
		<titulaciones>Grado de Gerencias, Técnica de administración
		</titulaciones>
		<sede>Valencia</sede>
		<observaciones>
			Su trabajo como jefe es encomiable.
			<meritos>Dedicación y buena energía</meritos>
		</observaciones>

	</empleado>

	<empleado id="A3">

		<nombre>Francina</nombre>
		<inicioContrato>2010/07/04</inicioContrato>
		<ocupaciónActual>Oficial 2º</ocupaciónActual>
		<ocupacionesAnteriores>Oficial 3º y peón</ocupacionesAnteriores>
		<jefe>A2</jefe>
		<sueldo>1.600</sueldo>
		<titulaciones>Tecnica especialista</titulaciones>
		<sede>Barcelona</sede>
		<observaciones>
			Se adapta al puesto de trabajo rápidamente.
		</observaciones>

	</empleado>

	<empleado id="A4">

		<nombre>Paquirrin</nombre>
		<inicioContrato>2020/12/08</inicioContrato>
		<ocupaciónActual>Peón</ocupaciónActual>
		<ocupacionesAnteriores></ocupacionesAnteriores>
		<jefe>A1</jefe>
		<sueldo>1.000</sueldo>
		<titulaciones>FP Básica técnico</titulaciones>
		<sede>Madrid</sede>
		<observaciones>
			<demeritos>Puntualidad</demeritos>
		</observaciones>

	</empleado>

	<empleado id="A5">

		<nombre>Antonio</nombre>
		<inicioContrato>2018/10/07</inicioContrato>
		<ocupaciónActual>Oficial 2º</ocupaciónActual>
		<ocupacionesAnteriores>Oficial 3º y Peón</ocupacionesAnteriores>
		<jefe>A2</jefe>
		<sueldo>1.800</sueldo>
		<titulaciones>Técnico especialista</titulaciones>
		<sede>Madrid</sede>
		<observaciones>
			Excelente organizador.
			<meritos>Organización</meritos>
		</observaciones>

	</empleado>

</empleados>
