=== profesorderedes/LenguajesDeMarcas/Tema3/hoja1/ejer02.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="libro">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="titulo" />
                <xs:element ref="precio" />
                <xs:element ref="publicacion" />
                <xs:element ref="autor" />
                <xs:element ref="capitulo" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute ref="codigo" />
        </xs:complexType>
    </xs:element>

    <xs:attribute name="codigo">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:length value="7" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="titulo" type="xs:string" />

    <xs:element name="precio">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="publicacion">
        <xs:complexType>
            <xs:attribute ref="fecha" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:attribute name="fecha" type="xs:date" />

    <xs:element name="autor" type="xs:string" />

    <xs:element name="capitulo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="titulo" />
                <xs:element ref="parrafo" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute ref="num" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:attribute name="num" type="xs:positiveInteger" />

    <xs:element name="parrafo">
        <xs:complexType mixed="true">
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="i" />
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name="i" type="xs:string" />

</xs:schema>

=== profesorderedes/LenguajesDeMarcas/Tema3/hoja1/ejer02.xml
<?xml version="1.0" encoding="UTF-8"?>

<libro codigo="LIB9801" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejer02.xsd">

    <titulo>Un gato callejero llamado Bob</titulo>
    <precio>15.10</precio>
    <publicacion fecha="2010-09-01" />
    <autor>James Bowen</autor>

    <capitulo num="1">
        <titulo>Compañeros de viaje</titulo>
        <parrafo>Según una famosa cita que leí en alguna parte, <i>a todos se nos
                ofrecen segundas oportunidades</i> cada día de nuestras vidas. Están ahí para que
            las tomemos, <i>pero simplemente no lo hacemos</i>. </parrafo>
        <parrafo>He pasado buena parte de mi vida confirmando esa cita. Se me
            dieron un montón de oportunidades, algunas veces a diario. Durante
            mucho tiempo no supe aprovecharlas, pero de pronto, a principios de
            la primavera de 2007, eso comenzó a cambiar.
        </parrafo>
    </capitulo>
    <capitulo num="2">
        <titulo>Camino a la recuperación</titulo>
        <parrafo>Llevo viviendo entre gatos desde que era niño, y siempre he
            sentido que les comprendía bien. A lo largo de mi infancia, mi
            familia tuvo varios siameses y, en un momento dado, también tuvimos
            un hermoso gato pardo.
</parrafo>
    </capitulo>

</libro>
