<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cine [
   
    <!ELEMENT cine (directores, peliculas)>
    <!ELEMENT directores (director)*>
    <!ELEMENT director (#PCDATA)>
        <!ATTLIST director coddir ID #REQUIRED>
    <!ELEMENT peliculas (pelicula)*>
    <!ELEMENT pelicula (#PCDATA)>
        <!ATTLIST pelicula direccion IDREFS #REQUIRED>
        
]>

<cine>
    <directores>
        <director coddir="CE">Clint Eastwood</director>
        <director coddir="JC">James Cameron</director>
    </directores>
    <peliculas>
        <pelicula direccion="JC">Avatar</pelicula>
        <pelicula direccion="CE">Mystic River</pelicula>
        <pelicula direccion="CE">Titanic</pelicula>
    </peliculas>
</cine>




