<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE articulos [
   
    <!ELEMENT articulos (#PCDATA | id | codigo)*>
    <!ELEMENT codigo (#PCDATA)>
    <!ELEMENT id (#PCDATA)>
    
]>

<articulos>
   
    <id>8608</id>
    Teclado
    <codigo>AF-18</codigo>
    <codigo>AF-45</codigo>
    Disquetera
    <id>7552</id>
    <id>4602</id>
    
</articulos>