<?xml version="1.0" encoding="UTF-8" ?>
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE pacientes [

    <!ELEMENT pacientes (paciente*)>
    <!ELEMENT paciente (nombre, (dni|num_seg_social))>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT dni (#PCDATA)>
    <!ELEMENT num_seg_social (#PCDATA)>

]>

<pacientes>
    <paciente>
        <nombre>Sofía Ruiz</nombre>
        <dni>29921001H</dni>
    </paciente>
    <paciente>
        <nombre>Manuel Campos</nombre>
        <num_seg_social>88399110J</num_seg_social>
    </paciente>
</pacientes>
