<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE pacientes [
    <!ELEMENT pacientes (paciente*)>
    <!ELEMENT paciente (nombre, (dni|num_seg_social), alergias?)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT dni (#PCDATA)>
    <!ELEMENT num_seg_social (#PCDATA)>
    <!ELEMENT alergias EMPTY>
]>

<pacientes>
    <paciente>
        <nombre>Sof√≠a Ruiz</nombre>
        <dni>29921001H</dni>
    </paciente>
    <paciente>
        <nombre>Manuel Campos</nombre>
        <num_seg_social>88399110J</num_seg_social>
        <alergias />
    </paciente>
</pacientes>